In [2]:
# 导包
import pandas as pd
import numpy as np

# 1.Series对象的创建及常用属性

## 1.1 Series对象的创建

In [ ]:
# Series对象: 它是Pandas的核心对象, 代表一行或者一列数据, 可以理解为是: 一维数组 + 对应的索引

In [ ]:
# 方式1: 把Python列表 -> Series对象, 默认索引, 从0开始, 逐个递增.
s1 = pd.Series([1, 2, 3])
print(s1)
print(type(s1))

In [ ]:
# 方式2: 把Python列表 -> Series对象, 指定索引.
s2 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
# print(s2)
s2

In [ ]:
# 方式3: 把Python元组 -> Series对象.
# s3 = pd.Series(('张三', '男', 23))
s3 = pd.Series(('张三', '男', 23), index=['name', 'gender', 'age'])
s3

In [ ]:
# 方式4: 把字典 -> Series对象. 键: 索引, 值: 数据.
s4 = pd.Series({'name': '张三', 'gender': '男', 'age': 23})
s4

In [ ]:
# 方式5: 把Numpy的ndarray对象 -> Series对象.
arr = np.arange(1, 6)
print(arr, type(arr))

In [ ]:
# s5 = pd.Series(arr)
s5 = pd.Series(arr, index=['a', 'b', 'c', 'd', 'e'])
s5

## 1.2 Series对象的常用属性

In [ ]:
# 1. 创建Series对象.
# data: 数据, index: 索引.
# s1 = pd.Series(data=[0, 1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E', 'F'])
s1 = pd.Series(data=[i for i in range(6)], index=[i for i in 'ABCDEF'])
s1

In [ ]:
# 演示Series的常用属性
print(s1.index)     # 获取索引列的值, Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

print(s1.values)    # 获取数值列.   [0 1 2 3 4 5]

# 根据索引获取数据.
print(s1['C'])

# 2. DataFrame对象的创建, 常用属性 和 方法

## 2.1 DataFrame对象的创建

In [ ]:
# 方式1: 把字典列表 -> DataFrame对象.   每组键值对 = 1列数据.
# 1. 定义数据集, 字典 + 列表的方式. 
data_dict = {
    '日期': ['2024-12-19', '2024-12-20', '2024-12-21'],
    '温度': [8, 5, 7], 
    '湿度': [65, 70, 60]
}

# 2. 把上述的 数据集 -> DataFrame对象.
# df1 = pd.DataFrame(data_dict)       # 默认索引从0开始, 逐个递增. 
# df1 = pd.DataFrame(data_dict, index=['a', 'b', 'c'])
df1 = pd.DataFrame(data=data_dict, index=['a', 'b', 'c'])
df1

In [ ]:
# 方式2: 把 列表 + 元组 => DataFrame对象.    列表的每个元素(元组) = 一行数据.
# 1. 定义数据集, 列表 + 元组的方式.
data_list = [
    ('2024-12-19', 8, 65), 
    ('2024-12-20', 5, 70),
    ('2024-12-21', 7, 60)
]
# 2. 把上述的数据集 -> DataFrame对象.
# df2 = pd.DataFrame(data=data_list)
# 
# 指定列名 和 索引.
df2 = pd.DataFrame(data=data_list, columns=['日期', '温度', '湿度'], index=['a', 'b', 'c'])
df2

In [ ]:
# 方式3: 把 Numpy的ndarray对象 -> DataFrame对象.
pd.DataFrame(np.arange(9).reshape(3, 3))

## 2.2 创建DataFrame对象的案例

In [ ]:
# 需求: 生成10个学生的5门功课的数据.
# 并将列名改为: ['语文', '数学', '英语', '物理', '化学'], 
# 索引列改为:   ['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9']

In [3]:
# 1. 生成10个学生的5门功课的数据.
score_data = np.random.randint(40, 101, size=(10, 5))
score_data

array([[ 56,  43,  57,  46,  91],
       [ 73,  94,  77,  80,  68],
       [ 71,  63,  80,  47,  61],
       [ 88,  94,  57,  88,  75],
       [ 59,  85,  64,  94,  94],
       [ 91,  87,  59,  80,  70],
       [ 89,  49,  70,  81,  45],
       [ 89, 100,  74,  60,  43],
       [ 90,  61,  65,  90,  99],
       [ 83,  98,  57,  87,  86]])

In [4]:
# 2. 把上述的ndarry对象 -> DataFrame对象.
score_df = pd.DataFrame(score_data)
score_df

    0    1   2   3   4
0  56   43  57  46  91
1  73   94  77  80  68
2  71   63  80  47  61
3  88   94  57  88  75
4  59   85  64  94  94
5  91   87  59  80  70
6  89   49  70  81  45
7  89  100  74  60  43
8  90   61  65  90  99
9  83   98  57  87  86

In [5]:
# 3. 定义列表, 记录: 列名.
col_names = ['语文', '数学', '英语', '物理', '化学']

# 4. 定义列表, 记录: 索引列.
index_names = ['同学' + str(i) for i in range(score_df.shape[0])]
index_names

['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9']

In [6]:
# 这种思路 = 先创建DataFrame对象, 再修改列名和索引列.
# 5. 修改DataFrame对象的列名和索引列.
score_df.columns = col_names
score_df.index = index_names

# 6. 打印修改后的结果.
score_df

     语文   数学  英语  物理  化学
同学0  56   43  57  46  91
同学1  73   94  77  80  68
同学2  71   63  80  47  61
同学3  88   94  57  88  75
同学4  59   85  64  94  94
同学5  91   87  59  80  70
同学6  89   49  70  81  45
同学7  89  100  74  60  43
同学8  90   61  65  90  99
同学9  83   98  57  87  86

In [ ]:
# 7. 上述代码也可以直接生成, 即: 构建DataFrame对象的时候, 直接指定索引和列名.
score_df2 = pd.DataFrame(data=score_data, columns=col_names, index=index_names)
score_df2

## 2.3 演示df对象的 常用属性

In [7]:
# shape属性: 获取df对象的形状, 格式为: (行数, 列数)
score_df.shape

(10, 5)

In [8]:
# index属性: 获取df对象的行索引
score_df.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [ ]:
# columns属性: 获取df对象的列索引

In [9]:
score_df.columns

Index(['语文', '数学', '英语', '物理', '化学'], dtype='object')

In [ ]:
# values属性: 获取df对象的数据, 返回ndarray

In [10]:
score_df.values

array([[ 56,  43,  57,  46,  91],
       [ 73,  94,  77,  80,  68],
       [ 71,  63,  80,  47,  61],
       [ 88,  94,  57,  88,  75],
       [ 59,  85,  64,  94,  94],
       [ 91,  87,  59,  80,  70],
       [ 89,  49,  70,  81,  45],
       [ 89, 100,  74,  60,  43],
       [ 90,  61,  65,  90,  99],
       [ 83,  98,  57,  87,  86]])

In [12]:
# T属性, 行列转置
score_df.T

    同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   56   73   71   88   59   91   89   89   90   83
数学   43   94   63   94   85   87   49  100   61   98
英语   57   77   80   57   64   59   70   74   65   57
物理   46   80   47   88   94   80   81   60   90   87
化学   91   68   61   75   94   70   45   43   99   86

In [13]:
# size属性, 获取df对象的元素个数, 行数 * 列数
score_df.size

50

In [14]:
# dtypes属性, 获取df对象的数据类型
score_df.dtypes

语文    int64
数学    int64
英语    int64
物理    int64
化学    int64
dtype: object

## 2.4 演示DataFrame的方法

In [16]:
# head方法 默认获取前5行数据
score_df.head(10)

     语文   数学  英语  物理  化学
同学0  56   43  57  46  91
同学1  73   94  77  80  68
同学2  71   63  80  47  61
同学3  88   94  57  88  75
同学4  59   85  64  94  94
同学5  91   87  59  80  70
同学6  89   49  70  81  45
同学7  89  100  74  60  43
同学8  90   61  65  90  99
同学9  83   98  57  87  86

In [18]:
# tail方法 默认获取最后5行数据
score_df.tail(3)

     语文   数学  英语  物理  化学
同学7  89  100  74  60  43
同学8  90   61  65  90  99
同学9  83   98  57  87  86

In [19]:
# describe方法: 获取数据的描述信息
score_df.describe()

              语文          数学         英语         物理         化学
count  10.000000   10.000000  10.000000  10.000000  10.000000
mean   78.900000   77.400000  66.000000  75.300000  73.200000
std    13.295363   21.349993   8.781293  17.745422  19.651407
min    56.000000   43.000000  57.000000  46.000000  43.000000
25%    71.500000   61.500000  57.500000  65.000000  62.750000
50%    85.500000   86.000000  64.500000  80.500000  72.500000
75%    89.000000   94.000000  73.000000  87.750000  89.750000
max    91.000000  100.000000  80.000000  94.000000  99.000000

In [20]:
# info方法: 获取数据的详细信息
score_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 同学0 to 同学9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   语文      10 non-null     int64
 1   数学      10 non-null     int64
 2   英语      10 non-null     int64
 3   物理      10 non-null     int64
 4   化学      10 non-null     int64
dtypes: int64(5)
memory usage: 780.0+ bytes

# 3 演示DataFrame的索引操作

## 3.1 修改索引

In [21]:
# 1. 观察源数据
score_df

     语文   数学  英语  物理  化学
同学0  56   43  57  46  91
同学1  73   94  77  80  68
同学2  71   63  80  47  61
同学3  88   94  57  88  75
同学4  59   85  64  94  94
同学5  91   87  59  80  70
同学6  89   49  70  81  45
同学7  89  100  74  60  43
同学8  90   61  65  90  99
同学9  83   98  57  87  86

In [25]:
# 2. 需求: 把列名改为: ['python基础', 'python进阶', '数据分析', '机器学习', '深度学习'], 行索引: stu_0,...
# 错误示范
# score_df['同学0'] = 'stu_0' # 只能改全部, 这个动作是给表新增一列
score_df.drop('同学0', axis=1, inplace=True)
score_df

In [27]:
# 3. 定义新列名
new_columns = ['python基础', 'python进阶', '数据分析', '机器学习', '深度学习']
# 4. 定义新行索引
new_idx_names = ['stu_' + str(i) for i in range(score_df.shape[0])]
# 5. 修改DataFrame对象的列名和索引列.
score_df.columns = new_columns
score_df.index = new_idx_names
score_df

       python基础  python进阶  数据分析  机器学习  深度学习
stu_0        56        43    57    46    91
stu_1        73        94    77    80    68
stu_2        71        63    80    47    61
stu_3        88        94    57    88    75
stu_4        59        85    64    94    94
stu_5        91        87    59    80    70
stu_6        89        49    70    81    45
stu_7        89       100    74    60    43
stu_8        90        61    65    90    99
stu_9        83        98    57    87    86

## 3.2 设置索引列

In [42]:
# 1. 准备数据
df = pd.DataFrame({'month': [1, 4, 7, 10],
                    'year': [2012, 2014, 2013, 2014],
                    'sale':[55, 40, 84, 31]})
df

   month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

In [43]:
# 2. 设置month为索引列
df.set_index('month', inplace=True)
# df.set_index('month', drop=False) # 不删除原索引列

In [44]:
# 3. 取消设置索引列
df.reset_index(inplace=True)
df

   month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31