In [2]:
# 导包
import pandas as pd
import numpy as np

# 1.Series对象的创建及常用属性

## 1.1 Series对象的创建

In [ ]:
# Series对象: 它是Pandas的核心对象, 代表一行或者一列数据, 可以理解为是: 一维数组 + 对应的索引

In [ ]:
# 方式1: 把Python列表 -> Series对象, 默认索引, 从0开始, 逐个递增.
s1 = pd.Series([1, 2, 3])
print(s1)
print(type(s1))

In [ ]:
# 方式2: 把Python列表 -> Series对象, 指定索引.
s2 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
# print(s2)
s2

In [ ]:
# 方式3: 把Python元组 -> Series对象.
# s3 = pd.Series(('张三', '男', 23))
s3 = pd.Series(('张三', '男', 23), index=['name', 'gender', 'age'])
s3

In [ ]:
# 方式4: 把字典 -> Series对象. 键: 索引, 值: 数据.
s4 = pd.Series({'name': '张三', 'gender': '男', 'age': 23})
s4

In [ ]:
# 方式5: 把Numpy的ndarray对象 -> Series对象.
arr = np.arange(1, 6)
print(arr, type(arr))

In [ ]:
# s5 = pd.Series(arr)
s5 = pd.Series(arr, index=['a', 'b', 'c', 'd', 'e'])
s5

## 1.2 Series对象的常用属性

In [ ]:
# 1. 创建Series对象.
# data: 数据, index: 索引.
# s1 = pd.Series(data=[0, 1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E', 'F'])
s1 = pd.Series(data=[i for i in range(6)], index=[i for i in 'ABCDEF'])
s1

In [ ]:
# 演示Series的常用属性
print(s1.index)     # 获取索引列的值, Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

print(s1.values)    # 获取数值列.   [0 1 2 3 4 5]

# 根据索引获取数据.
print(s1['C'])

# 2. DataFrame对象的创建, 常用属性 和 方法

## 2.1 DataFrame对象的创建

In [ ]:
# 方式1: 把字典列表 -> DataFrame对象.   每组键值对 = 1列数据.
# 1. 定义数据集, 字典 + 列表的方式. 
data_dict = {
    '日期': ['2024-12-19', '2024-12-20', '2024-12-21'],
    '温度': [8, 5, 7], 
    '湿度': [65, 70, 60]
}

# 2. 把上述的 数据集 -> DataFrame对象.
# df1 = pd.DataFrame(data_dict)       # 默认索引从0开始, 逐个递增. 
# df1 = pd.DataFrame(data_dict, index=['a', 'b', 'c'])
df1 = pd.DataFrame(data=data_dict, index=['a', 'b', 'c'])
df1

In [ ]:
# 方式2: 把 列表 + 元组 => DataFrame对象.    列表的每个元素(元组) = 一行数据.
# 1. 定义数据集, 列表 + 元组的方式.
data_list = [
    ('2024-12-19', 8, 65), 
    ('2024-12-20', 5, 70),
    ('2024-12-21', 7, 60)
]
# 2. 把上述的数据集 -> DataFrame对象.
# df2 = pd.DataFrame(data=data_list)
# 
# 指定列名 和 索引.
df2 = pd.DataFrame(data=data_list, columns=['日期', '温度', '湿度'], index=['a', 'b', 'c'])
df2

In [55]:
# 方式3: 把 Numpy的ndarray对象 -> DataFrame对象.
pd.DataFrame(np.arange(9).reshape(3, 3))

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

## 2.2 创建DataFrame对象的案例

In [57]:
# 需求: 生成10个学生的5门功课的数据.
# 并将列名改为: ['语文', '数学', '英语', '物理', '化学'], 
# 索引列改为:   ['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9']

In [3]:
# 1. 生成10个学生的5门功课的数据.
score_data = np.random.randint(40, 101, size=(10, 5))
score_data

array([[ 56,  67,  78,  67,  78],
       [ 67,  53,  79,  74,  88],
       [ 51,  56,  56,  74,  49],
       [ 57,  50,  84,  85, 100],
       [ 90,  55,  90,  74,  72],
       [ 72,  65,  74,  88,  93],
       [ 90,  43,  61,  67,  69],
       [ 67,  62,  70,  68,  47],
       [ 66,  78,  76,  94,  95],
       [ 83,  57,  67,  47,  62]], dtype=int32)

In [4]:
# 2. 把上述的ndarry对象 -> DataFrame对象.
score_df = pd.DataFrame(score_data)
score_df

    0   1   2   3    4
0  56  67  78  67   78
1  67  53  79  74   88
2  51  56  56  74   49
3  57  50  84  85  100
4  90  55  90  74   72
5  72  65  74  88   93
6  90  43  61  67   69
7  67  62  70  68   47
8  66  78  76  94   95
9  83  57  67  47   62

In [6]:
# 3. 定义列表, 记录: 列名.
col_names = ['语文', '数学', '英语', '物理', '化学']

# 4. 定义列表, 记录: 索引列.
index_names = ['同学' + str(i) for i in range(10)]
index_names

['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9']

In [69]:
# 这种思路 = 先创建DataFrame对象, 再修改列名和索引列.
# 5. 修改DataFrame对象的列名和索引列.
score_df.columns = col_names
score_df.index = index_names

# 6. 打印修改后的结果.
score_df

     语文   数学  英语  物理  化学
同学0  98   80  63  46  85
同学1  57   43  65  69  44
同学2  73   52  83  87  70
同学3  48   88  49  88  73
同学4  52   41  95  46  69
同学5  91  100  67  57  49
同学6  84   67  69  68  62
同学7  94   94  80  82  42
同学8  42   84  44  63  72
同学9  60   72  95  60  57

In [7]:
# 7. 上述代码也可以直接生成, 即: 构建DataFrame对象的时候, 直接指定索引和列名.
score_df2 = pd.DataFrame(data=score_data, columns=col_names, index=index_names)
score_df2

# 今天晚上要做的事儿
# 1. Numpy -> 创建, 属性, 基本方法, 统计方法, 去重, 排序, 矩阵乘法. 
# 2. Pandas -> 中美日三国GDP趋势图
# 3. Pandas的数据结构图 -> 自己绘制理解下 Series 和 DataFrame
# 4. Series -> 创建, 常用属性
# 5. DataFrame -> 创建,  [明天: 常用属性, 方法]

     语文  数学  英语  物理   化学
同学0  56  67  78  67   78
同学1  67  53  79  74   88
同学2  51  56  56  74   49
同学3  57  50  84  85  100
同学4  90  55  90  74   72
同学5  72  65  74  88   93
同学6  90  43  61  67   69
同学7  67  62  70  68   47
同学8  66  78  76  94   95
同学9  83  57  67  47   62