## 1.根据行列索引,获取数据

In [24]:
import pandas as pd
# import os
 # 改变相对路径
# os.chdir(r'D:\wordspace\ai_22_work_bj\pandasProject\day02')

In [25]:
# 1.准备数据
df = pd.read_csv('../data/stock_day.csv')
df

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,22.406,21.955,22.942,40827.52,42736.34,56007.50,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,21.938,21.929,23.022,35119.58,41871.97,56372.85,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,21.446,21.909,23.137,35397.58,39904.78,60149.60,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,21.366,21.923,23.253,33590.21,42935.74,61716.11,0.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,13.112,13.112,13.112,115090.18,115090.18,115090.18,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,12.820,12.820,12.820,98904.79,98904.79,98904.79,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,12.707,12.707,12.707,100812.93,100812.93,100812.93,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,12.610,12.610,12.610,117681.67,117681.67,117681.67,4.76
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,12.520,12.520,12.520,96291.73,96291.73,96291.73,3.30

### 1.1直接使用行列索引，先列后行

In [ ]:
# 2.根据行列索引 获取数据-->先列后行
#    列         行
df['open']['2018-02-27']
df['open']['2018-02-22']

#      行        列
# df['open']['2018-02-22']  # 报错，必须先列后行

df['high']['2018-02-23']   # 23.37

### 1.2 通过loc属性来获取, 先行后列

In [ ]:
# 3.通过loc属性来获取，只能通过：行索引+列名的方式来获取
# 格式：df.loc[行索引， 列名]
df.loc['2018-02-23', 'high']

In [ ]:
# 需求：获取从2018-02-27 - 2018-02-22的open列数据
df.loc['2018-02-27':'2018-02-22', 'open']


# 需求：获取从2018-02-27 - 2018-02-22的open, high, close, low列数据
df.loc['2018-02-27':'2018-02-22', 'open':'low']
df.loc['2018-02-27':'2018-02-22', ['open','high', 'close','low']]

# 需求：获取从2018-02-27 - 2018-02-22的所有列数据
df.loc['2018-02-27':'2018-02-22', :]         # 这里的：代表所有列

# 等价于直接打印df对象，获取所有数据
# df.loc[:, :]
df

### 1.3 通过iloc属性来获取, 先行后列, 只能通过：行号+列的编号方式来获取

In [ ]:
# 4.通过iloc属性来获取，只能通过：行号+列的编号方式来获取
# 格式: df.iloc[行号， 列的编号]
df.iloc[0, 0] # 0行0列的数据,即你看到的第一行第一列的数据->23.53

In [ ]:
# 需求：获取从2018-02-27 - 2018-02-22的open列数据
df.iloc[:4, 0]

# 需求：获取从2018-02-27 - 2018-02-22的open, high, close, low列数据
df.iloc[:4, :4]

# 需求：获取从2018-02-27 - 2018-02-22的所有列数据
df.iloc[:4]
df.iloc[:4, :]         # 这里的：代表所有列

# 等价于直接打印df对象，获取所有数据
# df.iloc[:, :]

# 观察效果
df.iloc[1:5:2, 2:5]

## 2.给列赋值,添加列,删除列

In [ ]:
# 1.查看源数据
df

In [26]:
# 2.删除列
df.drop(['ma5', 'ma10', 'ma20', 'v_ma5', 'v_ma10', 'v_ma20'], axis=1, inplace=True)  # 1->列, 0->行

In [ ]:
# 3.获取所有行的, open, high列
df.loc[:, ['open', 'high']]

In [ ]:
# 4.修改列值
# 细节: 列名存在就是修改值,列名不存在就是添加列          类似python的字典,键存在-->覆盖, 键不存在-->添加
#df['price_change']=1

# 5.新增列
df['day_diff'] = df['high'] - df['low']
df

In [ ]:
# 6.扩展 df['列名']和df.列名的区别, 如果是操作无特殊符号的列名,它们没区别.如果是有特殊符号(例如空格)的列名时, df['列名']是正确的
# df.open    # 可以
# df['open'] # 可以

# 7.添加一个包含空格符号的列名
# df['my name'] = '夯哥'

# 8. 获取my name列的值
df['my name']      # 可以
# df.my name       # 不可以,报错

## 3.DataFrame和Series的排序操作

In [27]:
# 1.查看数据源
df

,open,high,close,low,volume,price_change,p_change,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,0.58
...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30

In [29]:
# 2.根据单列值进行排序, 例如根据open列(开盘价)升序排序
df.sort_values('open')
df.sort_values('open', ascending=True)  #  ascending=True-->升序(默认)
df.sort_values('open', ascending=False) #  ascending=False-->降序

,open,high,close,low,volume,price_change,p_change,turnover
2015-06-15,34.99,34.99,31.69,31.69,199369.53,-3.52,-10.00,6.82
2015-06-12,34.69,35.98,35.21,34.01,159825.88,0.82,2.38,5.47
2015-06-10,34.10,36.35,33.85,32.23,269033.12,0.51,1.53,9.21
2017-11-01,33.85,34.34,33.83,33.10,232325.30,-0.61,-1.77,5.81
2015-06-11,33.17,34.98,34.39,32.51,173075.73,0.54,1.59,5.92
...,...,...,...,...,...,...,...,...
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-09-02,12.30,14.11,12.36,12.30,70201.74,-1.10,-8.17,2.40
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30

In [30]:
# 3.根据多列值进行排序
# 场景1:多列值排序规则一样, 例如:按照open升序, open一样,按照high升序
df.sort_values(['open', 'high'])
df.sort_values(['open', 'high'], ascending=True) # 效果同上.

,open,high,close,low,volume,price_change,p_change,turnover
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30
2015-09-02,12.30,14.11,12.36,12.30,70201.74,-1.10,-8.17,2.40
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
...,...,...,...,...,...,...,...,...
2015-06-11,33.17,34.98,34.39,32.51,173075.73,0.54,1.59,5.92
2017-11-01,33.85,34.34,33.83,33.10,232325.30,-0.61,-1.77,5.81
2015-06-10,34.10,36.35,33.85,32.23,269033.12,0.51,1.53,9.21
2015-06-12,34.69,35.98,35.21,34.01,159825.88,0.82,2.38,5.47
2015-06-15,34.99,34.99,31.69,31.69,199369.53,-3.52,-10.00,6.82

In [31]:
# 场景2:多列值排序规则一样, 例如:按照open升序, open一样,按照high降序
df.sort_values(['open', 'high'], ascending=True)
df.sort_values(['open', 'high'], ascending=False)

df.sort_values(['open', 'high'], ascending=[True, False])

,open,high,close,low,volume,price_change,p_change,turnover
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30
2015-09-02,12.30,14.11,12.36,12.30,70201.74,-1.10,-8.17,2.40
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
...,...,...,...,...,...,...,...,...
2015-06-11,33.17,34.98,34.39,32.51,173075.73,0.54,1.59,5.92
2017-11-01,33.85,34.34,33.83,33.10,232325.30,-0.61,-1.77,5.81
2015-06-10,34.10,36.35,33.85,32.23,269033.12,0.51,1.53,9.21
2015-06-12,34.69,35.98,35.21,34.01,159825.88,0.82,2.38,5.47
2015-06-15,34.99,34.99,31.69,31.69,199369.53,-3.52,-10.00,6.82

In [34]:
# 4.根据行索引排序
df.sort_index()                  # 默认升序
df.sort_index(ascending=True)    # 效果同上

df.sort_index(ascending=False)   # 降序
df

,open,high,close,low,volume,price_change,p_change,turnover
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,6.16
...,...,...,...,...,...,...,...,...
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,0.58
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,0.90
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,1.32
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,1.53
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39

In [35]:
# 5.无论是上述的根据值排序,还是根据行索引排序, 默认都是按照axis=0进行排序的
# df.sort_values('open', axis='rows')   # 根据open字段, 按照行排序, 默认:升序
df.sort_values('open', axis=0)        # 效果同上.

# df.sort_index('open', axis=1)           # 报错

,open,high,close,low,volume,price_change,p_change,turnover
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30
2015-09-02,12.30,14.11,12.36,12.30,70201.74,-1.10,-8.17,2.40
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
...,...,...,...,...,...,...,...,...
2015-06-11,33.17,34.98,34.39,32.51,173075.73,0.54,1.59,5.92
2017-11-01,33.85,34.34,33.83,33.10,232325.30,-0.61,-1.77,5.81
2015-06-10,34.10,36.35,33.85,32.23,269033.12,0.51,1.53,9.21
2015-06-12,34.69,35.98,35.21,34.01,159825.88,0.82,2.38,5.47
2015-06-15,34.99,34.99,31.69,31.69,199369.53,-3.52,-10.00,6.82

In [ ]:
# 6.Series对象的排序, 也有sort_index() 和 sort_values()两个函数, 用法和df对象一样
df.open.sort_index()                 # 按照索引: 升序
df.open.sort_index(ascending=False)  # 按照索引: 降序

df.open.sort_values()                # 按照值: 升序
df.open.sort_values(ascending=False) # 按照值: 降序