In [1]:
# 导包, 切换路径.
import pandas as pd
from sqlalchemy import create_engine
import json
# import os
# os.chdir(r'D:\workspace\ai_22_work_bj\pandasProject\day03')

# 1. pandas读写csv 和 tsv文件.

In [ ]:
# 此处略, 详见上个视频.  pd.read_csv(), df.to_csv()

# 2.Pandas读写SQL表.

## 2.1 准备动作

In [ ]:
# 去你的base沙箱下, 安装两个包, pymysql, sqlalchemy
# 注意: 如下的命令是去 DOS窗口中执行的. 

# pip install pymysql==1.0.2 -i https://pypi.tuna.tsinghua.edu.cn/simple/
# 如果后边的代码运行提示找不到sqlalchemy的包，和pymysql一样进行安装即可
# pip install sqlalchemy==2.0.0 -i https://pypi.tuna.tsinghua.edu.cn/simple/

## 2.2 Pandas写入数据到SQL表中

In [2]:
# 0. 确保你的MySQL服务已经成功启动, 且目标数据库(例如: day03数据库)已经创建成功.
# 1. 导包, 详见第1个单元格.
# from sqlalchemy import create_engine   其实导包动作写这里也行, 但是为了统一管理, 我已经统一的写到第1个单元格了. 

# 2. 读取csv文件, 获取到df对象, 它的信息就是要往SQL表中写的数据.
# index_col=0   设置编号为0的列(即: 第1列) 充当索引列. 
df = pd.read_csv('../data/csv示例文件.csv', encoding='gbk', index_col=0)
df

     birthday name   AKA
0    1960/5/7  刘海柱  职业法师
1    1978/9/1  赵金龙   大力哥
2  1984/12/27  周立齐  窃格瓦拉
3   1969/1/24   于谦  相声皇后

In [3]:
# 3. 创建引擎对象. 
# 参数解释: mysql+pymysql  -> 要操作的数据库, 具体用的包. 
# 参数解释: root:123456    -> 要操作的数据库的账号和密码.
# 参数解释: localhost:3306 -> 要操作的数据库所在的 Ip和端口号
# 参数解释: day03          -> 具体的要操作的 数据库名
# 参数解释: charset        -> 码表.
# 完整格式: 要操作的数据库+Python包名://数据库账号:密码@数据库IP:端口号/数据库名?charset=码表
engine = create_engine('mysql+pymysql://root:123456@localhost:3306/temp_test?charset=utf8')
engine

Engine(mysql+pymysql://root:***@localhost:3306/temp_test?charset=utf8)

In [4]:
# 4. 把df的数据 -> 导出到SQL表中.
# 参1: 目标表名,  参2: 数据库引擎对象,  参3: 是否导出索引列.  参4: 导出模式(覆盖模式/追加模式/报错)
# df.to_sql('stu', engine, index=False, if_exists='append')     # 追加
df.to_sql('stu', engine, index=False, if_exists='replace')     # 覆盖
print('导出数据到MySQL表成功!')

导出数据到MySQL表成功!

## 2.3 Pandas从SQL表中读取数据.

In [7]:
# 参1: SQL语句, 参2: 数据库引擎对象
# engine = create_engine('mysql+pymysql://root:123456@localhost:3306/day03?charset=utf8')
pd.read_sql('select * from stu;', engine)

     birthday name   AKA
0    1960/5/7  刘海柱  职业法师
1    1978/9/1  赵金龙   大力哥
2  1984/12/27  周立齐  窃格瓦拉
3   1969/1/24   于谦  相声皇后

In [8]:
# 当然, SQL语句也可以加载指定的列. 
# engine = create_engine('mysql+pymysql://root:123456@localhost:3306/day03?charset=utf8')
pd.read_sql('select name, AKA from stu;', engine)

  name   AKA
0  刘海柱  职业法师
1  赵金龙   大力哥
2  周立齐  窃格瓦拉
3   于谦  相声皇后

# 3. Pandas读写json格式

## 3.1 准备动作, 演示 Python字典 和 Json字符串互换.

In [ ]:
# 导包, import json, 同样, 详见第1个单元格.
# json解释: 它是一种特殊的字符串格式, 数值可以直接写, 其它类型要用 双引号包裹.

### 3.1.1 Python字典 -> Json字符串

In [3]:
# 1. 定义字典.
dict_data = {'name':'乔峰', 'age': 38, 'gender': '男'}

# 2. 把 字典 -> Json字符串.
json_str = json.dumps(dict_data, ensure_ascii=False)    # ensure_ascii参数意思是: 是否把中文转成ASCII码.
print(json_str)         # '{"name": "乔峰", "age": 38, "gender": "男"}'
print(type(json_str))   # <class 'str'>

{"name": "乔峰", "age": 38, "gender": "男"}
<class 'str'>

### 3.1.2 Json字符串 -> Python字典

In [4]:
# loads()函数, 可以加载json字符串, 转成Python字典. 
new_dict = json.loads(json_str)
print(new_dict)
print(type(new_dict))   # <class 'dict'>

{'name': '乔峰', 'age': 38, 'gender': '男'}
<class 'dict'>

## 3.2 Pandas读写json文件

In [6]:
# 1. Pandas读取json文件, 获取到 df对象.
# 参1: 文件路径, 参2: 读取格式, 参3: 是否是每行是一个对象.
df = pd.read_json('../data/test.json', orient='records', lines=True)
# df = pd.read_json('./data/my_out.json', orient='records', lines=True)
df

,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
3,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
4,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0

## 3.3 Pandas把df对象, 写到json文件.

In [ ]:
# df.to_json('./data/my_out.json')

# columns格式介绍: 列名作为key, 列值作为value, 即: 列名: {索引:值}, 例如: name:{0:乔峰,1:虚竹}
# df.to_json('./data/my_out.json', orient='columns')      # 效果同上.

# recors格式介绍: 列名作为键, 列值作为值.  然后把所有的json封装到1个列表中. 
# df.to_json('./data/my_out.json', orient='records')

# 依旧是 列名作为键, 列值作为值. 每个json对象占1行.
df.to_json('./data/my_out.json', orient='records', lines=True)
print('写出数据到json文件成功!')