In [2]:
# 导包, 切换路径.
import pandas as pd
# import os
# os.chdir(r'D:\workspace\ai_22_work_bj\pandasProject\day03')

# 1. DataFrame数据的增删改查操作

In [ ]:
## 1.0 准备动作, 读取数据, 获取df对象.
df1 = pd.read_csv('../data/1960-2019全球GDP数据.csv', encoding='gbk')
df1     # 9930行, 3列

# 基于 df1 拷贝出 df2
df2 = df1.head().copy()
df2     # 5行, 3列

## 1.1 增加列.

In [ ]:
# 方式1:  df[列名] = 值      会修改原数据.
df2['col1'] = 22                        # 该列会全用 22 来填充.
df2['col2'] = [1, 2, 3, 4, 5]           # 该列会用 列表中的每个值 来对应填充.  细节: 列表长度 = 行数.
df2['col3'] = df2.year * 2              # 还可以用其它列的值 来计算 填充. 
df2

In [ ]:
# 方式2: df.assign(列名 = 值)    不会修改原数据.
df2.assign(col1 = 22)
df2.assign(col2 = [1, 2, 3, 4, 5])
df2.assign(col3 = df2.year * 2)

In [ ]:
# assign() 还支持传入 Series对象. 
s1 = pd.Series(['段延庆', '叶二娘', '南海鳄神', '云中鹤'])       # 列表长度 = 行数, 如果不匹配, 用NaN来填充.
df2.assign(col4 = s1)

In [ ]:
# assign() 还支持 自定义函数. 
def my_fun(df):         # 这里的df就是要被处理的 DataFrame对象.
    return 'hello'

def my_fun1(df):
    return df.index.values * 2  # 返回该df的行索引 * 2

df2.assign(col5 = my_fun)
df2.assign(col6 = my_fun1)

In [ ]:
# 总结, assign() 可以用来增加列, 不能直接修改原数据, 且 assign()支持同时传入多个列. 
df2 = df2.assign(
    col1 = 22,
    col2 = [1, 2, 3, 4, 5],
    col3 = df2.year * 2,
    col4 = s1,
    col5 = my_fun,
    col6 = my_fun1
)
df2

## 1.2 删除和去重

In [ ]:
# 结论: Series去重可以用 drop_duplicates(), unique(),    DataFrame去重: 用 drop_duplicates()
# 1. 查看源数据. 
df2

In [ ]:
# 2. 删除行.  drop() 不会修改原数据. 
# df2.drop([0])               # 默认是删除: 行.
# df2.drop([0], axis=0)       # 默认是删除: 行, 效果同上.  0 -> 行, 1 -> 列.

# 同时删除多行.
df2.drop([0, 1, 4])         # 删除行索引值为0, 1, 4的行.

In [ ]:
# 3. 删除列.
df2.drop(['col1'], axis=1)              # 0 -> 行, 1 -> 列.
# df2.drop(['col1', 'col3'], axis=1)

In [ ]:
# 4. del 方式删除.      会修改原数据. 
del df2['col1']   
df2

In [ ]:
# 5. 去重.  drop_duplicates(), unique()
# df2.drop_duplicates()       # 整行去重. 

# df3 = df1[['country']].copy()        # df对象

# 去重, 
# df3.drop_duplicates(inplace=True)
# df3

# 去重. 
df3.unique()      # 报错.

In [ ]:
s1 = df1['country'].copy()   # Series对象
# s1.drop_duplicates()
s1.unique()

## 1.3 修改列.

In [65]:
# 1. 获取数据集.
df1 = pd.read_csv('../data/1960-2019全球GDP数据.csv', encoding='gbk')
df2 = df1.head(5).copy()
df2

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [42]:
# 方式1: 直接对源数据进行赋值处理.
df2['GDP'] = 33           # 直接修改原数据
df2

   year country  GDP
0  1960      美国   33
1  1960      英国   33
2  1960      法国   33
3  1960      中国   33
4  1960      日本   33

In [43]:
# 方式2: 不会修改原数据, 而是返回1个新的df对象
df2.assign(GDP = 66)   
# df2

   year country  GDP
0  1960      美国   66
1  1960      英国   66
2  1960      法国   66
3  1960      中国   66
4  1960      日本   66

In [63]:
# 方式3: replace函数来替换数据.   inplace=False -> 不会修改原数据,  True -> 修改原数据.

df2.year.replace(1960, 2024, inplace=True)      # 修改的是 Series对象  已不支持!!! 要不然就把year去掉

# 使用如下3种方式
# df2.replace({'year': {1960: 2024}}, inplace=True)
# df2['year'] = df2['year'].replace(1960, 2024)
# df2.loc[:, 'year'] = df2['year'].replace(1960, 2024)

# df2.replace('日本', '倭寇', inplace=True)        # 修改的是 DataFrame对象
df2

   year country           GDP
0  2024      美国  543300000000
1  2024      英国   73233967692
2  2024      法国   62225478000
3  2024      中国   59716467625
4  2024      倭寇   44307342950

In [67]:
# 同时修改多个值, 列表方式: 注意顺序要对应. 
df2.replace(['日本', '美国', 1960], ['扶桑', 'USA', 2024])

# 如果字典方式, 则无顺序要求. 
df2.replace({'中国':'龙国', 1960:2024, '日本':'倭寇'})

   year country           GDP
0  2024      美国  543300000000
1  2024      英国   73233967692
2  2024      法国   62225478000
3  2024      龙国   59716467625
4  2024      倭寇   44307342950

## 1.4 查看列.

In [3]:
# 1. 准备数据.
df1 = pd.read_csv('../data/1960-2019全球GDP数据.csv', encoding='gbk')
df1

      year   country           GDP
0     1960        美国  543300000000
1     1960        英国   73233967692
2     1960        法国   62225478000
3     1960        中国   59716467625
4     1960        日本   44307342950
...    ...       ...           ...
9925  2019  圣多美和普林西比     418637388
9926  2019        帕劳     268354919
9927  2019      基里巴斯     194647201
9928  2019        瑙鲁     118223430
9929  2019       图瓦卢      47271463

[9930 rows x 3 columns]

In [ ]:
# 2. 获取前n条数据.
df1.head()          # 默认是前5条
df1.head(10)        # 获取前10条数据.

In [ ]:
# 3. 获取后n条数据.
df1.tail()      # 默认是后5条
df1.tail(10)    # 默认是后10条

In [4]:
# 4. 获取1列或者多列数据. 
df1['year']     # 更通用, 列名即使带空格, 也可以. 例如:  df1['my col1']
df1.year        # 更推荐, 列名不带空格. 例如: df1.my col1 报错. 

df1[['year', 'country']]

      year   country
0     1960        美国
1     1960        英国
2     1960        法国
3     1960        中国
4     1960        日本
...    ...       ...
9925  2019  圣多美和普林西比
9926  2019        帕劳
9927  2019      基里巴斯
9928  2019        瑙鲁
9929  2019       图瓦卢

[9930 rows x 2 columns]

In [5]:
# 5. 索引下标切片 获取行. 
df2 = df1.head(10).copy()
df2

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
5  1960     加拿大   40461721692
6  1960     意大利   40385288344
7  1960      印度   37029883875
8  1960    澳大利亚   18577668271
9  1960      瑞典   15822585033

In [12]:
df2[:3]     # 前三行, 即: 索引0开始, 到索引3结束, 步长为: 1    包左不包右.
df2[3:]     # 索引3开始, 到df末尾结束, 步长为: 1    包左不包右.
df2[1:5:2]  # 索引1开始, 到索引5结束, 步长为: 2     包左不包右.
df2[1::3]   # 索引1开始, 到df末尾结束, 步长为: 3    包左不包右.
df2[-6:-2]  # 索引-6开始, 到索引-2结束, 步长为: 1   包左不包右.
df2[2:-2:]  # 索引2开始, 到索引-2结束, 步长为: 1    包左不包右.
#
df2[2:-2:-1]  # 索引2开始, 到索引-2结束, 步长为: -1    包左不包右.
#
df2[::-1]

   year country           GDP
9  1960      瑞典   15822585033
8  1960    澳大利亚   18577668271
7  1960      印度   37029883875
6  1960     意大利   40385288344
5  1960     加拿大   40461721692
4  1960      日本   44307342950
3  1960      中国   59716467625
2  1960      法国   62225478000
1  1960      英国   73233967692
0  1960      美国  543300000000

In [13]:
# 6. query()函数, 查看数据.
# 需求1: 查看中国的数据集. 
df1[df1.country == '中国']
df1.query('country == "中国"')

      year country             GDP
3     1960      中国     59716467625
107   1961      中国     50056868957
211   1962      中国     47209359005
316   1963      中国     50706799902
421   1964      中国     59708343488
525   1965      中国     70436266146
639   1966      中国     76720285969
755   1967      中国     72881631326
874   1968      中国     70846535055
993   1969      中国     79705906247
1114  1970      中国     92602973434
1243  1971      中国     99800958648
1373  1972      中国    113688000000
1503  1973      中国    138544000000
1634  1974      中国    144182000000
1765  1975      中国    163432000000
1898  1976      中国    153940000000
2033  1977      中国    174938000000
2173  1978      中国    149541000000
2310  1979      中国    178281000000
2449  1980      中国    191149000000
2596  1981      中国    195866000000
2745  1982      中国    205090000000
2896  1983      中国    230687000000
3049  1984      中国    259947000000
3203  1985      中国    309488000000
3359  1986      中国    300758000000
3520  1987      中国    272973000000
3682  1988      中国    312354000000
3847  1989      中国    347768000000
4012  1990      中国    360858000000
4195  1991      中国    383373000000
4375  1992      中国    426916000000
4557  1993      中国    444731000000
4740  1994      中国    564325000000
4927  1995      中国    734548000000
5118  1996      中国    863747000000
5311  1997      中国    961604000000
5503  1998      中国   1029040000000
5696  1999      中国   1094000000000
5889  2000      中国   1211350000000
6086  2001      中国   1339400000000
6284  2002      中国   1470550000000
6485  2003      中国   1660290000000
6686  2004      中国   1955350000000
6887  2005      中国   2285970000000
7089  2006      中国   2752130000000
7291  2007      中国   3550340000000
7495  2008      中国   4594310000000
7699  2009      中国   5101700000000
7902  2010      中国   6087160000000
8106  2011      中国   7551500000000
8312  2012      中国   8532230000000
8517  2013      中国   9570410000000
8723  2014      中国  10475700000000
8929  2015      中国  11061600000000
9134  2016      中国  11233300000000
9339  2017      中国  12310400000000
9543  2018      中国  13894800000000
9746  2019      中国  14279900000000

In [ ]:
# 需求2: 查看中美日三国, 2015 ~ 2019年的数据. 
df1.query('country in ["中国", "美国", "日本"]').query('year in [2015, 2016, 2017, 2018, 2019]')
df1.query('country in ["中国", "美国", "日本"] and year in [2015, 2016, 2017, 2018, 2019]')   # 效果同上.
df1.query('country in ["中国", "美国", "日本"] & year in [2015, 2016, 2017, 2018, 2019]')     # 效果同上.

## 1.5 排序相关

In [ ]:
# 1. 准备数据.
df1 = pd.read_csv('./data/1960-2019全球GDP数据.csv', encoding='gbk')
df1

In [ ]:
# 2. 按照行索引排序
df1.sort_index()                    # 默认, 升序.
df1.sort_index(ascending=False)     # ascending=True -> 升序, False -> 降序

In [ ]:
# 3. 按照 列值 排序.
# 场景1: 按照 单列值 排序.
df1.sort_values('GDP')                      # 默认: 升序
df1.sort_values('GDP', ascending=False)     # 降序.

# 场景2: 按照 多列值 排序, 排序方式一样.
df1.sort_values(['year', 'GDP'])                        # 按照 year列 升序排列, 年份一样再按照 GDP列 升序 排序.
df1.sort_values(['year', 'GDP'], ascending= False)      # 按照 year列 降序排列, 年份一样再按照 GDP列 降序 排序.

# 场景3: 按照 多列值 排序, 排列方式不同, 例如: 按照 year列 降序, GDP升序.
df1.sort_values(['year', 'GDP'], ascending=[False, True])

In [14]:
# 4. 排序(排名)函数, rank()函数.
df2 = pd.DataFrame({
    '姓名':['小明', '小美', '小强', '小兰'],
    '成绩':[100, 90, 90, 80]
})
df2

   姓名   成绩
0  小明  100
1  小美   90
2  小强   90
3  小兰   80

In [22]:
# 用rank()函数, 对上述内容做排名. 
df2.rank(ascending=False)                       # 按照成绩, 降序排名. 
df2.rank(ascending=False, method='average')     # 效果同上, 按照成绩, 降序排名.  评分一致, 取平均值
df2.rank(ascending=False, method='min')         # 评分一致, 取最小值.
df2.rank(ascending=False, method='max')         # 评分一致, 取最大值.
#
# # 掌握如下这个, 上述的了解排序原理即可.
df2.rank(ascending=False, method='dense')       # 数值相同, 评分一致.  等价于SQL中的 dense_rank()

# 只对成绩列做排名，不同method效果对比
df2['排名_average'] = df2['成绩'].rank(ascending=False, method='average')
# df2['排名_min'] = df2['成绩'].rank(ascending=False, method='min')
# df2['排名_max'] = df2['成绩'].rank(ascending=False, method='max')
# df2['排名_dense'] = df2['成绩'].rank(ascending=False, method='dense')
df2

   姓名   成绩  排名_average
0  小明  100         1.0
1  小美   90         2.5
2  小强   90         2.5
3  小兰   80         4.0