In [ ]:
# 导包, 切换路径.
import pandas as pd
import numpy as np
# import os
# os.chdir(r'D:\workspace\ai_22_work_bj\pandasProject\day03')

# 全局取消证书验证
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

# 1. 缺失值判断

In [ ]:
# 1. 加载数据, 获取df对象.
df = pd.read_csv('../data/movie.csv')
df

In [ ]:
# 2. 查看每列的值的分布情况, 即: 查看df的 详细 信息.
df.info()

In [ ]:
# 3. 判断每列缺失值的个数. 
df.isnull()     # 判断是否为空.
df.notnull()    # 判断是否不为空

# 查看每列的 缺失值的个数.
df.isnull().sum()     

# 查看每列的 非缺失值的个数.
df.notnull().sum()

# pd.notnull(df): 判断df中 列值是否不为空. True -> 不为空, False -> 为空
# np.all(df对象 == True): 判断df对象中所有元素是否为True.  是 -> True,  否则 -> False
np.all(pd.notnull(df) == True)

# 2.处理缺失值 -> 删除缺失值 dropna()

In [ ]:
# 1. 查看源数据
df.info()

In [ ]:
# 2. 删除缺失值.
df.dropna(inplace=True)       # 默认: axis = 0 -> 删除行.
# df.dropna(inplace=True, axis=1) # axis = 1 -> 删除列.

# 3. 查看删除缺失值后的数据情况.
df.info()

# 每列 空值  数量
df.isnull().sum()

# 3. 处理缺失值 -> 填充缺失值 fillna()

In [ ]:
# 1. 查看原数据
df.info()

df

In [ ]:
# 2. 填充缺失值, 例如: 用该列值的 平均值填充. 
# 查看 Revenue (Millions) 列的 平均值.   82.956376
# df['Revenue (Millions)'].mean()       # 82.956376

# 用 Revenue (Millions) 列的平均值, 来填充 所有列的 NaN(缺失值), 虽然实现了效果, 但是不够灵活. 
df.fillna(df['Revenue (Millions)'].mean())

In [28]:
# 3. 用 每列的平均值, 来填充 每列的缺失值.
# 3.1 看看有缺失值的两列的 平均值.
df['Revenue (Millions)'].mean()     # 82.95637614678898
df['Metascore'].mean()              # 58.98504273504273

# 3.2 遍历 df的所有列, 获取到每个列的信息.
for col_name in df.columns:
    # print(col_name)     # 就是df的每个列名.
    # 3.3 判断当前列 是否有缺失值, 如果有, 就用该列的平均值来填充.
    # 方式1: 根据该列的空值的数量来判断. 
    if df[col_name].isnull().sum() > 0:
    
    # 方式2: 根据 np.all()函数来判断, 判断: 包含空值的列.
    # if not np.all(pd.notnull(df[col_name])):
        print(col_name)       # 打印下列名.
        
        # 3.4 具体的用该列的平均值填充的动作.
        df[col_name] = df[col_name].fillna(df[col_name].mean())

# 3.5 查看处理后的情况.
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.130000,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.460000,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.120000,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.320000,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.020000,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,82.956376,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.540000,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.010000,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,82.956376,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.640000,11.0

# 4. 如果有特殊标记, 先转换, 然后再处理缺失值.

In [29]:
# 1. 加载源数据.
wis = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data")
wis

     1000025  5   1  1.1  1.2  2 1.3   3  1.4  1.5  2.1
0    1002945  5   4    4    5  7  10   3    2    1    2
1    1015425  3   1    1    1  2   2   3    1    1    2
2    1016277  6   8    8    1  3   4   3    7    1    2
3    1017023  4   1    1    3  2   1   3    1    1    2
4    1017122  8  10   10    8  7  10   9    7    1    4
..       ... ..  ..  ...  ... ..  ..  ..  ...  ...  ...
693   776715  3   1    1    1  3   2   1    1    1    2
694   841769  2   1    1    1  2   1   1    1    1    2
695   888820  5  10   10    3  7   3   8   10    2    4
696   897471  4   8    6    4  3   4  10    6    1    4
697   897471  4   8    8    5  4   5  10    4    1    4

[698 rows x 11 columns]

In [30]:
# 2. 查看每列的缺失值情况.
wis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   1000025  698 non-null    int64
 1   5        698 non-null    int64
 2   1        698 non-null    int64
 3   1.1      698 non-null    int64
 4   1.2      698 non-null    int64
 5   2        698 non-null    int64
 6   1.3      698 non-null    object
 7   3        698 non-null    int64
 8   1.4      698 non-null    int64
 9   1.5      698 non-null    int64
 10  2.1      698 non-null    int64
dtypes: int64(10), object(1)
memory usage: 60.1+ KB

In [36]:
# 3. 把特殊标记 -> NaN (细节: 空可以用 Numpy中的 nan, NaN, NAN来表示, 效果都一样)
print(np.nan)
wis.replace('?', np.nan, inplace=True)
wis

nan

     1000025  5   1  1.1  1.2  2 1.3   3  1.4  1.5  2.1
0    1002945  5   4    4    5  7  10   3    2    1    2
1    1015425  3   1    1    1  2   2   3    1    1    2
2    1016277  6   8    8    1  3   4   3    7    1    2
3    1017023  4   1    1    3  2   1   3    1    1    2
4    1017122  8  10   10    8  7  10   9    7    1    4
..       ... ..  ..  ...  ... ..  ..  ..  ...  ...  ...
693   776715  3   1    1    1  3   2   1    1    1    2
694   841769  2   1    1    1  2   1   1    1    1    2
695   888820  5  10   10    3  7   3   8   10    2    4
696   897471  4   8    6    4  3   4  10    6    1    4
697   897471  4   8    8    5  4   5  10    4    1    4

[698 rows x 11 columns]

In [37]:
# 4. 删除缺失值.
wis.dropna(inplace=True)
wis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 682 entries, 0 to 697
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   1000025  682 non-null    int64
 1   5        682 non-null    int64
 2   1        682 non-null    int64
 3   1.1      682 non-null    int64
 4   1.2      682 non-null    int64
 5   2        682 non-null    int64
 6   1.3      682 non-null    object
 7   3        682 non-null    int64
 8   1.4      682 non-null    int64
 9   1.5      682 non-null    int64
 10  2.1      682 non-null    int64
dtypes: int64(10), object(1)
memory usage: 63.9+ KB

In [ ]:
df = pd.DataFrame({
    'name': ['乔峰', '虚竹', '段誉'],
    'age': [18, '♠', 20],
    'gender': ['男', '男', '♠'],
})
df