In [ ]:
# 导包
import pandas as pd
# import os
# os.chdir(r'D:\workspace\ai_22_work_bj\pandasProject\day03')

In [ ]:
# 准备数据.
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                        'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                        'key2': ['K0', 'K0', 'K0', 'K0'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']})
df3 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                        'key2': ['K0', 'K0', 'K0', 'K0'],
                        'E': ['E0', 'E1', 'E2', 'E3'],
                        'F': ['F0', 'F1', 'F2', 'F3']},index=[10, 11, 12, 13])

In [ ]:
# 1. 查看数据.
left
# right

# 1. 演示 pd.concat() 合并方式

In [6]:
# 1. 合并left 和 right, 默认是: 纵向合并(0 -> 列), 参考: 列名.
# 即: 列名一样的合并, 不一样的有值就用值填充, 无值就用NaN填充. 
pd.concat([left, right])
# pd.concat([left, right], axis=0)                       # 纵向合并 -> 列合并.
pd.concat([left, right], axis=0, ignore_index=True)    # 纵向合并 -> 列合并, 忽略索引.

  key1 key2    A    B    C    D
0   K0   K0   A0   B0  NaN  NaN
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2  NaN  NaN
3   K2   K1   A3   B3  NaN  NaN
4   K0   K0  NaN  NaN   C0   D0
5   K1   K0  NaN  NaN   C1   D1
6   K1   K0  NaN  NaN   C2   D2
7   K2   K0  NaN  NaN   C3   D3

In [8]:
# 2. 合并left 和 right, 指定: 横向合并(1 -> 行), 参考: 行索引.
# pd.concat([left, right], axis=1)    # 横向合并 -> 行合并(axis = 1)

# 验证: 横向合并参考行索引, 不匹配用NaN填充.
pd.concat([left, df3], axis=1)      # 横向合并 -> 行合并(axis = 1)

   key1 key2    A    B key1 key2    E    F
0    K0   K0   A0   B0  NaN  NaN  NaN  NaN
1    K0   K1   A1   B1  NaN  NaN  NaN  NaN
2    K1   K0   A2   B2  NaN  NaN  NaN  NaN
3    K2   K1   A3   B3  NaN  NaN  NaN  NaN
10  NaN  NaN  NaN  NaN   K0   K0   E0   F0
11  NaN  NaN  NaN  NaN   K1   K0   E1   F1
12  NaN  NaN  NaN  NaN   K1   K0   E2   F2
13  NaN  NaN  NaN  NaN   K2   K0   E3   F3

In [9]:
# pd.concat()总结:  
#   1. 可以同时拼接多个df对象.    
#   2. concat可以做行合并(axis=1, 横向合并), 也可以做列合并(axis=0, 纵向合并, 默认的).    
#   3. 行合并参考行索引, 列合并参考列名, 不匹配用NaN填充.
#   4. concat()默认是: outer(满外连接)

pd.concat([left, right, df3])

   key1 key2    A    B    C    D    E    F
0    K0   K0   A0   B0  NaN  NaN  NaN  NaN
1    K0   K1   A1   B1  NaN  NaN  NaN  NaN
2    K1   K0   A2   B2  NaN  NaN  NaN  NaN
3    K2   K1   A3   B3  NaN  NaN  NaN  NaN
0    K0   K0  NaN  NaN   C0   D0  NaN  NaN
1    K1   K0  NaN  NaN   C1   D1  NaN  NaN
2    K1   K0  NaN  NaN   C2   D2  NaN  NaN
3    K2   K0  NaN  NaN   C3   D3  NaN  NaN
10   K0   K0  NaN  NaN  NaN  NaN   E0   F0
11   K1   K0  NaN  NaN  NaN  NaN   E1   F1
12   K1   K0  NaN  NaN  NaN  NaN   E2   F2
13   K2   K0  NaN  NaN  NaN  NaN   E3   F3

# 2. 演示 pd.merge() 合并方式

In [ ]:
# 1. 查看源数据
left
right

# pd.merge总结:  
#   1. 一次只能合并两个df对象.    
#   2. merge()只能做 行的合并, 即: 横向合并.   
#   3. 行合并时参考: 关联字段, 类似于 MySQL的 join连接查询. 
#   4. merge()默认是: 内连接

In [ ]:
# 场景1: 用1个字段做关联. 
# 2. 演示: 左外连接.
# 参1: 第1个df对象.
# 参2: 第2个df对象,
# 参3: 连接方式 -> left(左外连接), right(右外连接), inner(内连接), outer(全连接, 满外连接).
pd.merge(left, right, how='left', on='key1')

# 3. 演示: 右外连接
pd.merge(left, right, how='right', on='key1')

# 4. 演示: 内连接
pd.merge(left, right, how='inner', on='key1')
pd.merge(left, right, on='key1')        # 效果同上, 默认是内连接.

# 5. 演示: 满外连接.
pd.merge(left, right, how='outer', on='key1')

In [ ]:
# 场景2: 用 多个字段(这里是2个字段做关联)
# 1. 演示: 内连接.  关联字段是: key1 和 key2 作为整体进行关联.             两个df的交集.
pd.merge(left, right, how='inner', on=['key1', 'key2'])
pd.merge(left, right, on=['key1', 'key2']) # 效果同上, 默认是: 内连接.

# 2. 演示: 左外连接, 关联字段是: key1 和 key2 作为整体进行关联.             左边df的全集 + 右边df的交集
pd.merge(left, right, how='left', on=['key1', 'key2'])

# 3. 演示: 右外连接, 关联字段是: key1 和 key2 作为整体进行关联.             右边df的全集 + 左边df的交集
pd.merge(left, right, how='right', on=['key1', 'key2'])

# 4. 演示: 满外连接, 关联字段是: key1 和 key2 作为整体进行关联.             左边df的全集 + 左右边df的交集 + 右边df的全集
pd.merge(left, right, how='outer', on=['key1', 'key2'])
pd.merge(left, right, how='outer', on=['key1', 'key2'])