In [1]:
# 导包
import time
import numpy as np 
import pandas as pd
from sqlalchemy import create_engine
from pyecharts.charts import Bar3D              # 需要安装下, 即: pip install pyecharts
from pyecharts.commons.utils import JsCode
import pyecharts.options as opts

# 改变相对路径. 
# import os
# os.chdir(r'D:\workspace\ai_22_work_bj\pandasProject\day05')

# 1. 读取数据

In [2]:
# 1. 定义变量, 记录表名. 
sheet_names = ['2015', '2016', '2017', '2018', '会员等级']

# 2. 读取上述的excel表, 获取到数据, 结果是: 字典类型,  键: Excel表名, 值: 该表的数据封装成的DataFrame对象.
sheet_dict = pd.read_excel('./data/sales.xlsx', sheet_name=sheet_names)
sheet_dict      # {'2015': df对象, '2016': df对象, '2017': df对象, '2018': df对象, '会员等级': df对象, }

{'2015':               会员ID         订单号       提交日期    订单金额
 0      15278002468  3000304681 2015-01-01   499.0
 1      39236378972  3000305791 2015-01-01  2588.0
 2      38722039578  3000641787 2015-01-01   498.0
 3      11049640063  3000798913 2015-01-01  1572.0
 4      35038752292  3000821546 2015-01-01    10.1
 ...            ...         ...        ...     ...
 30769  39368100847  4281994827 2015-12-31   828.0
 30770       409757  4282010457 2015-12-31   199.0
 30771  38380526114  4282017675 2015-12-31   208.0
 30772     28074988  4282019440 2015-12-31    89.0
 30773  39460363230  4282025309 2015-12-31   719.0

 [30774 rows x 4 columns],
 '2016':               会员ID         订单号       提交日期     订单金额
 0      39288120141  4282025766 2016-01-01    76.00
 1      39293812118  4282037929 2016-01-01  7599.00
 2      27596340905  4282038740 2016-01-01   802.00
 3      15111475509  4282043819 2016-01-01    65.00
 4      38896594001  4282051044 2016-01-01    95.00
 ...            ...         ...        ...      ...
 41273  35336052906  4324910145 2016-12-31    99.00
 41274  39305835721  4324910148 2016-12-31   238.89
 41275  39296945352  4324910770 2016-12-31   765.00
 41276  14791026234  4324911025 2016-12-31    45.80
 41277  16779755770  4324911048 2016-12-31   119.00

 [41278 rows x 4 columns],
 '2017':               会员ID         订单号       提交日期    订单金额
 0      38765290840  4324911135 2017-01-01  1799.0
 1      39305832102  4324911213 2017-01-01   369.0
 2      34190994969  4324911251 2017-01-01   189.0
 3      38986333210  4324911283 2017-01-01   169.0
 4          4271359  4324911355 2017-01-01    78.0
 ...            ...         ...        ...     ...
 50834  39155833075  4338762307 2017-12-31    96.0
 50835  29523124076  4338762514 2017-12-31    99.0
 50836      7807573  4338762906 2017-12-31   258.0
 50837  36642530033  4338762958 2017-12-31   286.0
 50838  39155901156  4338763879 2017-12-31   249.0

 [50839 rows x 4 columns],
 '2018':               会员ID         订单号       提交日期    订单金额
 0      39229691808  4338764262 2018-01-01  3646.0
 1      39293668916  4338764363 2018-01-01  3999.0
 2      35059646224  4338764376 2018-01-01    10.1
 3          1084397  4338770013 2018-01-01   828.0
 4          3349915  4338770121 2018-01-01  3758.0
 ...            ...         ...        ...     ...
 81344  39229485704  4354225182 2018-12-31   249.0
 81345  39229021075  4354225188 2018-12-31    89.0
 81346  39288976750  4354230034 2018-12-31    48.5
 81347     26772630  4354230163 2018-12-31  3196.0
 81348  39455580335  4354235084 2018-12-31  2999.0

 [81349 rows x 4 columns],
 '会员等级':                会员ID  会员等级
 0            100090     3
 1       10012905801     1
 2       10012935109     1
 3       10013498043     1
 4       10014087899     4
 ...             ...   ...
 154380       998138     3
 154381       998298     1
 154382       998571     4
 154383       999563     4
 154384       999951     1

 [154385 rows x 2 columns]}

In [ ]:
# 3. 查看上述数据的 类型.
print(type(sheet_dict))     # <class 'dict'>

# 4. 从字典中 获取 2015表 的数据.
sheet_dict['2015']

# 5. 查看 2015表数据的 详细信息. 
sheet_dict['2015'].info()

# 6. 查看 2015表数据的 统计信息.
sheet_dict['2015'].describe()

# 7. 查看 2016表数据的 详细信息. 
sheet_dict['2016'].info()

In [15]:
# 8. 查看 各表的 详细信息, 统计信息. 
for i in sheet_names:
    print(sheet_dict[i])
    sheet_dict[i].info()
    sheet_dict[i].describe()

              会员ID         订单号       提交日期    订单金额 max_year_date
0      15278002468  3000304681 2015-01-01   499.0    2015-12-31
1      39236378972  3000305791 2015-01-01  2588.0    2015-12-31
2      38722039578  3000641787 2015-01-01   498.0    2015-12-31
3      11049640063  3000798913 2015-01-01  1572.0    2015-12-31
4      35038752292  3000821546 2015-01-01    10.1    2015-12-31
...            ...         ...        ...     ...           ...
30769  39368100847  4281994827 2015-12-31   828.0    2015-12-31
30770       409757  4282010457 2015-12-31   199.0    2015-12-31
30771  38380526114  4282017675 2015-12-31   208.0    2015-12-31
30772     28074988  4282019440 2015-12-31    89.0    2015-12-31
30773  39460363230  4282025309 2015-12-31   719.0    2015-12-31

[30574 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 30574 entries, 0 to 30773
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           30574 non-null  int64
 1   订单号            30574 non-null  int64
 2   提交日期           30574 non-null  datetime64[ns]
 3   订单金额           30574 non-null  float64
 4   max_year_date  30574 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 1.4 MB
              会员ID         订单号       提交日期     订单金额 max_year_date
0      39288120141  4282025766 2016-01-01    76.00    2016-12-31
1      39293812118  4282037929 2016-01-01  7599.00    2016-12-31
2      27596340905  4282038740 2016-01-01   802.00    2016-12-31
3      15111475509  4282043819 2016-01-01    65.00    2016-12-31
4      38896594001  4282051044 2016-01-01    95.00    2016-12-31
...            ...         ...        ...      ...           ...
41273  35336052906  4324910145 2016-12-31    99.00    2016-12-31
41274  39305835721  4324910148 2016-12-31   238.89    2016-12-31
41275  39296945352  4324910770 2016-12-31   765.00    2016-12-31
41276  14791026234  4324911025 2016-12-31    45.80    2016-12-31
41277  16779755770  4324911048 2016-12-31   119.00    2016-12-31

[41001 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 41001 entries, 0 to 41277
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           41001 non-null  int64
 1   订单号            41001 non-null  int64
 2   提交日期           41001 non-null  datetime64[ns]
 3   订单金额           41001 non-null  float64
 4   max_year_date  41001 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 1.9 MB
              会员ID         订单号       提交日期    订单金额 max_year_date
0      38765290840  4324911135 2017-01-01  1799.0    2017-12-31
1      39305832102  4324911213 2017-01-01   369.0    2017-12-31
2      34190994969  4324911251 2017-01-01   189.0    2017-12-31
3      38986333210  4324911283 2017-01-01   169.0    2017-12-31
4          4271359  4324911355 2017-01-01    78.0    2017-12-31
...            ...         ...        ...     ...           ...
50834  39155833075  4338762307 2017-12-31    96.0    2017-12-31
50835  29523124076  4338762514 2017-12-31    99.0    2017-12-31
50836      7807573  4338762906 2017-12-31   258.0    2017-12-31
50837  36642530033  4338762958 2017-12-31   286.0    2017-12-31
50838  39155901156  4338763879 2017-12-31   249.0    2017-12-31

[50451 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 50451 entries, 0 to 50838
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           50451 non-null  int64
 1   订单号            50451 non-null  int64
 2   提交日期           50451 non-null  datetime64[ns]
 3   订单金额           50451 non-null  float64
 4   max_year_date  50451 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 2.3 MB
              会员ID         订单号       提交日期    订单金额 max_year_date
0      39229691808  4338764262 2018-01-01  3646.0    2018-12-31
1      39293668916  4338764363 2018-01-01  3999.0    2018-12-31
2      35059646224  4338764376 2018-01-01    10.1    2018-12-31
3          1084397  4338770013 2018-01-01   828.0    2018-12-31
4          3349915  4338770121 2018-01-01  3758.0    2018-12-31
...            ...         ...        ...     ...           ...
81344  39229485704  4354225182 2018-12-31   249.0    2018-12-31
81345  39229021075  4354225188 2018-12-31    89.0    2018-12-31
81346  39288976750  4354230034 2018-12-31    48.5    2018-12-31
81347     26772630  4354230163 2018-12-31  3196.0    2018-12-31
81348  39455580335  4354235084 2018-12-31  2999.0    2018-12-31

[80801 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 80801 entries, 0 to 81348
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           80801 non-null  int64
 1   订单号            80801 non-null  int64
 2   提交日期           80801 non-null  datetime64[ns]
 3   订单金额           80801 non-null  float64
 4   max_year_date  80801 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 3.7 MB
               会员ID  会员等级
0            100090     3
1       10012905801     1
2       10012935109     1
3       10013498043     1
4       10014087899     4
...             ...   ...
154380       998138     3
154381       998298     1
154382       998571     4
154383       999563     4
154384       999951     1

[154385 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154385 entries, 0 to 154384
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   会员ID    154385 non-null  int64
 1   会员等级    154385 non-null  int64
dtypes: int64(2)
memory usage: 2.4 MB

# 2. 数据的预处理

In [3]:
# 1. 处理缺失值, 过滤掉不合法的数据, 新增: max_year_date列
# 1.1 遍历, 获取到前4张表, 即: 2015 ~ 2018年的所有表数据.
for i in sheet_names[:-1]:
    # 1.2 处理缺失值, 方案: 删除.
    sheet_dict[i] = sheet_dict[i].dropna()
    # 1.3 过滤出合法值, 即: 金额在1元以上的订单.
    sheet_dict[i] = sheet_dict[i][sheet_dict[i]['订单金额'] > 1]
    # 1.4 新增1列, 用于表示: 固定时间(统计时间)
    sheet_dict[i]['max_year_date'] = sheet_dict[i]['提交日期'].max()

In [ ]:
# 2 查看处理后的数据信息. 
for i in sheet_names:
    print(sheet_dict[i].info())        # 表的详细信息
    print(sheet_dict[i].describe())    # 表的统计信息

In [4]:
# 3. 合并数据集, 获取到最终的处理后的 DataFrame对象.
# 3.1 获取到前4张表的数据, 拼接成新的DataFrame对象.
data_merge = pd.concat(list(sheet_dict.values())[:-1], ignore_index=True)

# 3.2 给表新增1列: 年.
data_merge['year'] = data_merge['max_year_date'].dt.year

# 3.3 给表新增1列 date_interval, 表示: 购买商品的间隔时间, 即: max_year_date - 提交日期
data_merge['date_interval'] = data_merge['max_year_date'] - data_merge['提交日期']
# 3.4 把上述的时间间隔, 转成对应的 天数(数值)
data_merge['date_interval'] = data_merge['date_interval'].dt.days
# 3.5 查看最终合并后的结果.
data_merge

,会员ID,订单号,提交日期,订单金额,max_year_date,year,date_interval
0,15278002468,3000304681,2015-01-01,499.0,2015-12-31,2015,364
1,39236378972,3000305791,2015-01-01,2588.0,2015-12-31,2015,364
2,38722039578,3000641787,2015-01-01,498.0,2015-12-31,2015,364
3,11049640063,3000798913,2015-01-01,1572.0,2015-12-31,2015,364
4,35038752292,3000821546,2015-01-01,10.1,2015-12-31,2015,364
...,...,...,...,...,...,...,...
202822,39229485704,4354225182,2018-12-31,249.0,2018-12-31,2018,0
202823,39229021075,4354225188,2018-12-31,89.0,2018-12-31,2018,0
202824,39288976750,4354230034,2018-12-31,48.5,2018-12-31,2018,0
202825,26772630,4354230163,2018-12-31,3196.0,2018-12-31,2018,0
202826,39455580335,4354235084,2018-12-31,2999.0,2018-12-31,2018,0

# 3. 数据 -> 统计分析

In [5]:
# 1. 按照 year, 会员ID分组, 分别计算: r(最近购买时间), f(频次), m(金额)三项的 原始数据.
rfm_gb = data_merge.groupby(['year', '会员ID'], as_index=False).agg({
    'date_interval': 'min',         # 间隔时间的最小值 -> r(recency)
    '订单号': 'count',               # 购买频次的数量 -> f(frequency)
    '订单金额': 'sum'                # 购买金额的和 -> m(monetary)
})

# 2. 修改列名.
rfm_gb.columns = ['year', '会员ID', 'r', 'f', 'm']
rfm_gb

        year         会员ID    r  f       m
0       2015          267  197  2   105.0
1       2015          282  251  1    29.7
2       2015          283  340  1  5398.0
3       2015          343  300  1   118.0
4       2015          525   37  3   213.0
...      ...          ...  ... ..     ...
148586  2018  39538034299  272  1    49.0
148587  2018  39538034662  189  1  3558.0
148588  2018  39538035729  179  1  3699.0
148589  2018  39545237824  275  1    49.0
148590  2018  39546136285  163  1    19.9

[148591 rows x 5 columns]

In [6]:
# 3. 因为使用的是三分法, 所以需要确定4个值, 才能划分: 3个区间. 自定义区间即可.
# 3.1 查看 r, f, m的 分位数. 
rfm_gb.iloc[:, 2:].describe().T

# 3.2 自定义区间.
r_bins = [-1, 79, 255, 365]
f_bins = [0, 2, 5, 130]
m_bins = [0, 69, 1199, 206252]

In [9]:
# 4. 具体的划分区间的动作, 获取 r, f, m三项的 具体评分. 
# 场景1: 演示 自动划分区间, 即: 给定区间数, 由Pandas自动划分区间.
pd.cut(rfm_gb['r'], bins=3).unique()        # Categories类型: [(-0.365, 121.667], (121.667, 243.333], (243.333, 365.0]]

# 场景2: 演示 自定义区间, 即: 我们给定数字, 由Pandas进行具体的划分.
pd.cut(rfm_gb['r'], bins=r_bins).unique()   # Categories类型: [(-1, 79], (79, 255], (255, 365]]

# 场景3: 自定义区间 + 评分.
pd.cut(rfm_gb['r'], bins=r_bins, labels=[3, 2, 1])      # 可以, 但是不推荐, 因为值写死了. 
pd.cut(rfm_gb['f'], bins=f_bins, labels=[1, 2, 3])      # 可以, 但是不推荐, 因为值写死了. 
pd.cut(rfm_gb['m'], bins=m_bins, labels=[1, 2, 3])      # 可以, 但是不推荐, 因为值写死了. 

# 场景4: 最终版, 自定义区间 + 评分(结合区间值 列表的长度获取)
# r(Recency): 最后一次购买的时间, 越小越好, 评分是: 3, 2, 1
rfm_gb['r_label'] = pd.cut(rfm_gb['r'], bins=r_bins, labels=[i for i in range(len(r_bins) - 1, 0, -1)]) # range(3, 0, -1) -> [3, 2, 1]    
# f(Frequency): 购买频次, 越大越好, 评分是: 1, 2, 3
rfm_gb['f_label'] = pd.cut(rfm_gb['f'], bins=f_bins, labels=[i for i in range(1, len(f_bins))]) # range(1, 4) -> [1, 2, 3]
# # m(Monetary): 购买金额, 越大越好, 评分是: 1, 2, 3
rfm_gb['m_label'] = pd.cut(rfm_gb['m'], bins=m_bins, labels=[i for i in range(1, len(m_bins))]) # range(1, 4) -> [1, 2, 3]
rfm_gb

        year         会员ID    r  f       m r_label f_label m_label
0       2015          267  197  2   105.0       2       1       2
1       2015          282  251  1    29.7       2       1       1
2       2015          283  340  1  5398.0       1       1       3
3       2015          343  300  1   118.0       1       1       2
4       2015          525   37  3   213.0       3       2       2
...      ...          ...  ... ..     ...     ...     ...     ...
148586  2018  39538034299  272  1    49.0       1       1       1
148587  2018  39538034662  189  1  3558.0       2       1       3
148588  2018  39538035729  179  1  3699.0       2       1       3
148589  2018  39545237824  275  1    49.0       1       1       1
148590  2018  39546136285  163  1    19.9       2       1       1

[148591 rows x 8 columns]

In [10]:
# 5. 获取具体的 用户分群结果值. 
# 思路1: 加权, r_lable * 权重 + f_label * 权重 + m_label * 权重
# 例如: r_label * 0.2 + f_label * 0.3 + m_label * 0.5

# 思路2: 拼接思路 即: r_label + f_label + m_label -> 字符串类型. 
rfm_gb['r_label'] = rfm_gb['r_label'].astype(str)
rfm_gb['f_label'] = rfm_gb['f_label'].astype(str)
rfm_gb['m_label'] = rfm_gb['m_label'].astype(str)

rfm_gb['rfm_group'] = rfm_gb['r_label'] + rfm_gb['f_label'] + rfm_gb['m_label']
rfm_gb

        year         会员ID    r  f       m r_label f_label m_label rfm_group
0       2015          267  197  2   105.0       2       1       2       212
1       2015          282  251  1    29.7       2       1       1       211
2       2015          283  340  1  5398.0       1       1       3       113
3       2015          343  300  1   118.0       1       1       2       112
4       2015          525   37  3   213.0       3       2       2       322
...      ...          ...  ... ..     ...     ...     ...     ...       ...
148586  2018  39538034299  272  1    49.0       1       1       1       111
148587  2018  39538034662  189  1  3558.0       2       1       3       213
148588  2018  39538035729  179  1  3699.0       2       1       3       213
148589  2018  39545237824  275  1    49.0       1       1       1       111
148590  2018  39546136285  163  1    19.9       2       1       1       211

[148591 rows x 9 columns]

# 4. 保存分析结果

In [ ]:
# 1. 保存结果到 -> Excel表.
rfm_gb.to_excel('./data/sale_rfm_group.xlsx', index=False)
print('导出信息到Excel表 成功!')

In [ ]:
# 2. 保存结果到 -> Excel表, 例如: rfm_db数据库,  rfm_score 表.
# 2.1 创建引擎对象.
engine = create_engine('mysql+pymysql://root:123456@localhost:3306/rfm_db?charset=utf8')
engine

In [ ]:
# 2.2 导出数据到MySQL表中.
# 场景1: 导出指定字段.
# rfm_gb[['year', '会员ID', 'rfm_group']].to_sql('rfm_score', engine, index=False, if_exists='replace')

# 场景2: 导出所有字段. 
rfm_gb.to_sql('rfm_score', engine, index=False, if_exists='replace')
print('导出数据到MySQL表 成功!')

In [ ]:
# 2.3 查看导出后的结果, 即: 从SQL表中读取数据.
pd.read_sql('select * from rfm_score limit 100;', engine)
pd.read_sql('select count(1) from rfm_score;', engine)

# 5. 数据可视化.

In [13]:
# 1. 按照 用户分群类型(rfm_group), 年份分组, 统计会员总数. 
# 思路1: value_counts()
# rfm_gb.groupby(['rfm_group', 'year'])['会员ID'].value_counts()

# 思路2: groupby() + 聚合函数.
display_data = rfm_gb.groupby(['rfm_group', 'year'], as_index=False).agg({'会员ID': 'count'})
# 修改列名.
display_data.columns = ['rfm_group', 'year', 'number']
# 修改 rfm_group的类型为 int类型.
display_data['rfm_group'] = display_data['rfm_group'].astype(int)
# 查看最终结果.
display_data

    rfm_group  year  number
0         111  2015    2180
1         111  2016    1498
2         111  2017    3169
3         111  2018    2271
4         112  2015    3811
..        ...   ...     ...
83        332  2018      24
84        333  2015      15
85        333  2016      28
86        333  2017      87
87        333  2018     355

[88 rows x 3 columns]

In [16]:
# 2. 可视化, 显示图形

# 颜色池
range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
               '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']

range_max = int(display_data['number'].max())
c = (
    Bar3D()#设置了一个3D柱形图对象
    .add(
        "",#图例
        [d.tolist() for d in display_data.values],#数据
        xaxis3d_opts=opts.Axis3DOpts(type_="category", name='分组名称'),#x轴数据类型，名称，rfm_group
        yaxis3d_opts=opts.Axis3DOpts(type_="category", name='年份'),#y轴数据类型，名称，year
        zaxis3d_opts=opts.Axis3DOpts(type_="value", name='会员数量'),#z轴数据类型，名称，number
    )
    .set_global_opts( # 全局设置
        visualmap_opts=opts.VisualMapOpts(max_=range_max, range_color=range_color), #设置颜色，及不同取值对应的颜色
        title_opts=opts.TitleOpts(title="RFM分组结果"),#设置标题
    )
)
c.render() 		      # 数据保存到本地的网页中.
# c.render_notebook() #在notebook中显示

'/Users/apple/Desktop/Playground/jupyter_study/RFM案例/render.html'